show_env_vars:
  stage: build
  variables:
    JOB_VARIABLE: 'this is an env var defined for this job'
    MY_VARIABLE: 'test overwrite environment variable' # does NOT overwrite
  script:
    # Custom environment variables defined in Gitlab CI Settings (must be unmasked in UI if these should be logged)
    - echo $MY_VARIABLE
    - echo $K8S_SECRET_MY_APP_VARIABLE
    # Environment variables defined in this job under `variables`
    - echo $JOB_VARIABLE
    # Predefined environment variables: https://gitlab.com/help/ci/variables/predefined_variables.md
    - echo $ARTIFACT_DOWNLOAD_ATTEMPTS
    - echo $CHAT_INPUT
    - echo $CHAT_CHANNEL
    - echo $CI
    - echo $CI_BUILDS_DIR
    - echo $CI_CONCURRENT_ID
    - echo $CI_CONCURRENT_PROJECT_ID
    - echo $CI_COMMIT_BEFORE_SHA
    - echo $CI_COMMIT_DESCRIPTION
    - echo $CI_COMMIT_MESSAGE
    - echo $CI_COMMIT_REF_NAME
    - echo $CI_COMMIT_REF_SLUG
    - echo $CI_COMMIT_SHA
    - echo $CI_COMMIT_SHORT_SHA
    - echo $CI_COMMIT_TAG
    - echo $CI_COMMIT_TITLE
    - echo $CI_CONFIG_PATH
    - echo $CI_DEBUG_TRACE
    - echo $CI_DEPLOY_PASSWORD
    - echo $CI_DEPLOY_USER
    - echo $CI_DISPOSABLE_ENVIRONMENT
    - echo $CI_ENVIRONMENT_NAME
    - echo $CI_ENVIRONMENT_SLUG
    - echo $CI_ENVIRONMENT_URL
    - echo $CI_JOB_ID
    - echo $CI_JOB_MANUAL
    - echo $CI_JOB_NAME
    - echo $CI_JOB_STAGE
    - echo $CI_JOB_TOKEN
    - echo $CI_JOB_URL
    - echo $CI_MERGE_REQUEST_ID
    - echo $CI_MERGE_REQUEST_IID
    - echo $CI_MERGE_REQUEST_PROJECT_ID
    - echo $CI_MERGE_REQUEST_PROJECT_PATH
    - echo $CI_MERGE_REQUEST_PROJECT_URL
    - echo $CI_MERGE_REQUEST_REF_PATH
    - echo $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    - echo $CI_MERGE_REQUEST_SOURCE_BRANCH_SHA
    - echo $CI_MERGE_REQUEST_SOURCE_PROJECT_ID
    - echo $CI_MERGE_REQUEST_SOURCE_PROJECT_PATH
    - echo $CI_MERGE_REQUEST_SOURCE_PROJECT_URL
    - echo $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - echo $CI_MERGE_REQUEST_TARGET_BRANCH_SHA
    - echo $CI_MERGE_REQUEST_TITLE
    - echo $CI_MERGE_REQUEST_ASSIGNEES
    - echo $CI_MERGE_REQUEST_MILESTONE
    - echo $CI_MERGE_REQUEST_LABELS
    - echo $CI_NODE_INDEX
    - echo $CI_NODE_TOTAL
    - echo $CI_API_V4_URL
    - echo $CI_PAGES_DOMAIN
    - echo $CI_PAGES_URL
    - echo $CI_PIPELINE_ID
    - echo $CI_PIPELINE_IID
    - echo $CI_PIPELINE_SOURCE
    - echo $CI_PIPELINE_TRIGGERED
    - echo $CI_PIPELINE_URL
    - echo $CI_PROJECT_DIR
    - echo $CI_PROJECT_ID
    - echo $CI_PROJECT_NAME
    - echo $CI_PROJECT_NAMESPACE
    - echo $CI_PROJECT_PATH
    - echo $CI_PROJECT_PATH_SLUG
    - echo $CI_PROJECT_URL
    - echo $CI_PROJECT_VISIBILITY
    - echo $CI_COMMIT_REF_PROTECTED
    - echo $CI_REGISTRY
    - echo $CI_REGISTRY_IMAGE
    - echo $CI_REGISTRY_PASSWORD
    - echo $CI_REGISTRY_USER
    - echo $CI_REPOSITORY_URL
    - echo $CI_RUNNER_DESCRIPTION
    - echo $CI_RUNNER_EXECUTABLE_ARCH
    - echo $CI_RUNNER_ID
    - echo $CI_RUNNER_REVISION
    - echo $CI_RUNNER_TAGS
    - echo $CI_RUNNER_VERSION
    - echo $CI_SERVER
    - echo $CI_SERVER_NAME
    - echo $CI_SERVER_REVISION
    - echo $CI_SERVER_VERSION
    - echo $CI_SERVER_VERSION_MAJOR
    - echo $CI_SERVER_VERSION_MINOR
    - echo $CI_SERVER_VERSION_PATCH
    - echo $CI_SHARED_ENVIRONMENT
    - echo $GET_SOURCES_ATTEMPTS
    - echo $GITLAB_CI
    - echo $GITLAB_USER_EMAIL
    - echo $GITLAB_USER_ID
    - echo $GITLAB_USER_LOGIN
    - echo $GITLAB_USER_NAME
    - echo $RESTORE_CACHE_ATTEMPTS
    - echo $GITLAB_FEATURES
    # Show all environment variables
    - export